project:
  type: website
  output-dir: ../docs

website:
  title: "Deep Thought"
  site-url: https://blog.lucasmartino.com
  description: "A great blog"
  #page-footer: "Copyright (c) 2024, " 
  navbar:
    left:
      - href: index.qmd
        text: Início
      - about.qmd    
    tools:
      # - icon: twitter
      #   href: https://twitter.com
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/lucas-martino/lucas-martino.github.io
          - text: Report a Bug
            href:  https://github.com/lucas-martino/lucas-martino.github.io/issues
  comments:
    giscus:
      repo: lucas-martino/lucas-martino.github.io

execute:
  freeze: auto